FROM python:3.9

WORKDIR /app

COPY ../requirements.txt .
# COPY ../app .
# COPY ../migrations .



# COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

# RUN flask db upgrade
# RUN 
# RUN flask seed all

# CMD [ "python3"]
# CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
# CMD ["flask", "run", "--host=0.0.0.0"]     