"""empty message
Revision ID: ef022bde02d3
Revises: d65b57defda4
Create Date: 2022-03-22 12:29:10.129846
"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = 'ef022bde02d3'
down_revision = 'd65b57defda4'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_comment_id_fkey', 'images', type_='foreignkey')
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('images_comment_id_fkey', 'images', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
