"""empty message
Revision ID: adca872d8c6e
Revises: 52dbc51c6e4f
Create Date: 2022-02-28 17:28:24.041490
"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = 'adca872d8c6e'
down_revision = '52dbc51c6e4f'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'location_id')
    # ### end Alembic commands ###
