"""empty message
Revision ID: 4e71de5b8042
Revises: 6054ec06bcc3
Create Date: 2024-09-26 03:57:30.751351
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4e71de5b8042'
down_revision = '6054ec06bcc3'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vote')
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='vote_location_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='vote_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vote_pkey')
    )
    op.drop_table('votes')
    # ### end Alembic commands ###
