"""empty message
Revision ID: 578ad2bc87e9
Revises: 4e71de5b8042
Create Date: 2024-11-05 08:47:30.698033
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '578ad2bc87e9'
down_revision = '4e71de5b8042'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address', sa.String(length=564), nullable=True))
    op.add_column('locations', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('locations', sa.Column('zipcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'zipcode')
    op.drop_column('locations', 'state')
    op.drop_column('locations', 'city')
    op.drop_column('locations', 'address')
    # ### end Alembic commands ###
